plugins {
    id("groovy")
    id("io.micronaut.application") version "4.6.1"
    id("io.micronaut.aot") version "4.6.1"
    id("com.gradleup.shadow") version "8.3.6"
    id("maven-publish")
}

version = "0.0.1-SNAPSHOT"
group = "org.maurodata.plugins"

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation("info.picocli:picocli")
    implementation("io.micronaut.groovy:micronaut-runtime-groovy")
    implementation("io.micronaut.picocli:micronaut-picocli")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    compileOnly("info.picocli:picocli-codegen")
    compileOnly("io.micronaut.serde:micronaut-serde-processor")
    runtimeOnly("ch.qos.logback:logback-classic")
    implementation("io.micronaut:micronaut-jackson-databind")
    implementation group: 'org.apache.groovy', name: 'groovy-json', version: '4.0.21'
    runtimeOnly("org.yaml:snakeyaml")

    implementation("io.micronaut.sql:micronaut-jdbc-hikari")
//    runtimeOnly("com.zaxxer:HikariCP:5.1.0")

    implementation (group: 'org.duckdb', name: 'duckdb_jdbc', version: '1.2.0')
    implementation 'org.maurodata:mauro-domain:0.0.2-beta'

    implementation group: 'org.apache.commons', name: 'commons-csv', version: '1.12.0'
}


application {
    mainClass = "mauro.plugin.duckdb.MauroPluginCSVCommand"
}

java {
    sourceCompatibility = JavaVersion.toVersion("17")
    targetCompatibility = JavaVersion.toVersion("17")
}


micronaut {
    runtime("netty")
    testRuntime("spock2")
    processing {
        incremental(true)
        annotations("uk.ac.ox.softeng.mauro.*", "org.maurodata.*")
    }
    aot {
        // Please review carefully the optimizations enabled below
        // Check https://micronaut-projects.github.io/micronaut-aot/latest/guide/ for more details
        optimizeServiceLoading = false
        convertYamlToJava = false
        precomputeOperations = true
        cacheEnvironment = true
        optimizeClassLoading = true
        deduceEnvironment = true
        optimizeNetty = true
    }
}

plugins.withId("maven-publish") {
    publishing {
        publications {
            create("mavenJava", MavenPublication) {
                from(components["java"])
                artifactId = "${rootProject.name}"
            }
        }

        repositories {
            maven {
                name = "MauroSnapshotRepository"
                url = "https://mauro-repository.com/libs-snapshot-local"
                credentials(PasswordCredentials)
                authentication {
                    basic(BasicAuthentication)
                }
            }
        }
    }
}

